# Generated by Django 2.2.3 on 2019-07-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('updateTo', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('star', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
    ]
