# Generated by Django 2.2.3 on 2019-08-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nameMd5', models.CharField(max_length=255)),
                ('episode', models.CharField(max_length=255)),
                ('episodeUrl', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='video_detail',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video_detail',
            name='filmLength',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='issueTime',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='language',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='nameMd5',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='scoreTime',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='source',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='todayPlay',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='totalPlay',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='totalScore',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_detail',
            name='updateTime',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
